Fix compiler errors on Windows (#460)
* update flash-attention module to include fixes for windows

* fix flash_attention setup: add -std=c++17

* silence warnings for now

* use -std=c++17 to fix error: expected a comma (the one-argument version of static_assert is not enabled in this mode) errors

* fix all C2975:expected compile-time constant expression, C2131:expression did not evaluate to a constant by using /Zc:lambda (enables conforming lambda grammar and processing support)

* fix restrict is not allowed errors in kernel_backward.h

* fix error: asm operand type size(4) does not match type/size implied by constraint l in epilogue_predicated_tile_iterator.h

* fix error C3495

* /Zc:preprocessor appears to be needed to avoid error: expected a type specifier;error: type name is not allowed;error: too many arguments for class template AttentionKernel in forward_f16.cu for example

* fix LNK2001: unresolved external symbol PyInit__C error

* reenable warnings

* in setup.py, make -std=c++17 windows specific

* ran  black . --exclude third_party/

* apply linter suggestions

* ifdef syntax instead of removing the lambda entirely