fMHA: Explain reason why inputs are not supported
Should make debugging easier

**EXAMPLE**

```
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : torch.Size([1, 4096, 160, 128]) (torch.float32)
     key         : torch.Size([1, 4096, 160, 128]) (torch.float32)
     value       : torch.Size([1, 4096, 160, 127]) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    (value.shape[-1] % 4) != 0
`flshattF` is not supported because:
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    query.shape[-1] != value.shape[-1]
`tritonflashattF` is not supported because:
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    query.shape[-1] != value.shape[-1]
`smallkF` is not supported because:
    query.shape[-1] != value.shape[-1]
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 128
```

ghstack-source-id: b94263f9ef62017451f94a2f8855a0d95a81700d
Pull Request resolved: https://github.com/fairinternal/xformers/pull/416

__original_commit__ = fairinternal/xformers@d1bc8c6fc220d29326e305d33314bb9908b36484